import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
	{
		ignores: [
			'dist', // autogenerated by Nuxt
			'.output', // autogenerated by Nuxt
			'.nuxt', // autogenerated by Nuxt
			'types/roadiz.d.ts', // filled with autogenerated types from Roadiz
			'node_modules',
			'prismicio-types.d.ts',
		],
	},
).append({
	rules: {
		// ✅ Autorise les tabs comme indentation
		'@stylistic/no-tabs': ['error', { allowIndentationTabs: true }],

		// ✅ Force l’indentation avec tab
		'@stylistic/indent': ['error', 'tab'],
	},
})
