import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
    {
        ignores: [
            'dist', // autogenerated by Nuxt
            '.output', // autogenerated by Nuxt
            '.nuxt', // autogenerated by Nuxt
            'types/roadiz.d.ts', // filled with autogenerated types from Roadiz
            'node_modules',
            'prismicio-types.d.ts',
            'projects-source',
            'app/slices/index.ts',
        ],
    },
).append({
    rules: {
        '@stylistic/indent': ['error', 4],
        '@stylistic/function-paren-newline': ['error', 'consistent'],
        'vue/html-indent': ['error', 4],
    },
})
