import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
    {
        ignores: [
            'dist', // autogenerated by Nuxt
            '.output', // autogenerated by Nuxt
            '.nuxt', // autogenerated by Nuxt
            'types/roadiz.d.ts', // filled with autogenerated types from Roadiz
            'node_modules',
        ],
    },
)
