[[redirects]]
    from = "/home"
    to = "/"
    status = 301

[[redirects]]
    from = "/projet/elec"
    to = "/"
    status = 301

[[redirects]]
    from = "/projet/audiome"
    to = "/"
    status = 301

[[redirects]]
    from = "/projet/lmd"
    to = "/lmd-playground"
    status = 301

[[redirects]]
    from = "/projet/hugo"
    to = "/hugo-tomasi"
    status = 301

[[redirects]]
    from = "/projet/pogo"
    to = "/pogote-moi-cette-fonte"
    status = 301


